import Head from "next/head";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";

export default function Home({ newsResults }) {
  return (
    <>
      <Head>
        <title>Twitter Clone V4</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/** sidebar */}
        <Sidebar />
        {/**feed */}
        <Feed />
        {/**widgets */}
        <Widgets newsResults={newsResults.articles} />
        {/** Model */}
      </main>
    </>
  );
}

////https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());
  return {
    props: {
      newsResults,
    },
  };
}
